version: 2.1
orbs:
  hugo: circleci/hugo@1.3.0
  aws-cli: circleci/aws-cli@3.1.5 
jobs: 
  install-aws-cli:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          role-arn: "arn:aws:iam::957873794635:role/oidc_s3"
          aws-region: us-east-2
workflows: 
  main: 
    jobs:
      - hugo/build:
          html-proofer: false
      - install-aws-cli:
          requires: 
            - hugo/build
