version: 2.1
orbs:
  hugo: circleci/hugo@1.3.0
  aws-cli: circleci/aws-cli@3.1.5 

jobs: 
  install-aws-cli:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
       

workflows: 
  main: 
    jobs:
      - hugo/build:
          html-proofer: false
      - install-aws-cli:
          requires: 
            - hugo/build
