version: 2.1
orbs:
  hugo: circleci/hugo@1.3.0

jobs: 
  build:
    executor: hugo/default
    steps: 
      - hugo/hugo-build
      - persist_to_workspace:
          root: public
  print-generated:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: public
      - run: ls public
       

workflows: 
  main: 
    jobs:
      
      - print-generated
          requires: hugo/build
