version: 2.1
orbs:
  hugo: circleci/hugo@1.3.0

jobs: 
  print-generated:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - run: cd public
      - run: 
          name: authenticate
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email $GITHUB_EMAIL
            git checkout web-deploy
       

workflows: 
  main: 
    jobs:
      - hugo/build:
          html-proofer: false
      - print-generated:
          requires: 
            - hugo/build
